# Features

In [2]:
import pandas as pd

df = pd.read_csv("../data/processed/cleaned_matches.csv")
df["date"] = pd.to_datetime(df["date"])

df = df.sort_values("date")
df.head()

,date,home_team,away_team,home_score,away_score,tournament,city,country,neutral,year,month,result
0,2000-01-04,Egypt,Togo,2.0,1.0,Friendly,Aswan,Egypt,False,2000,1,Home Win
1,2000-01-07,Tunisia,Togo,7.0,0.0,Friendly,Tunis,Tunisia,False,2000,1,Home Win
2,2000-01-08,Trinidad and Tobago,Canada,0.0,0.0,Friendly,Port of Spain,Trinidad and Tobago,False,2000,1,Draw
3,2000-01-09,Burkina Faso,Gabon,1.0,1.0,Friendly,Ouagadougou,Burkina Faso,False,2000,1,Draw
4,2000-01-09,Guatemala,Armenia,1.0,1.0,Friendly,Los Angeles,United States,True,2000,1,Draw

In [3]:
# Store historical team statistics
from collections import defaultdict
team_stats = defaultdict(
    lambda: {
        "matches": 0,
        "wins": 0,
        "draws": 0,
        "losses": 0,
        "goals_scored": 0,
        "goals_conceded": 0,
    }
)

# Feature storage
home_matches_played = []
away_matches_played = []

home_win_rate = []
away_win_rate = []

home_draw_rate = []
away_draw_rate = []

home_loss_rate = []
away_loss_rate = []

home_avg_goals_scored = []
away_avg_goals_scored = []

home_avg_goals_conceded = []
away_avg_goals_conceded = []

In [4]:
for _, row in df.iterrows():

    home = row["home_team"]
    away = row["away_team"]

    home_stats = team_stats[home]
    away_stats = team_stats[away]


    # HOME TEAM FEATURES
    hm = home_stats["matches"]

    home_matches_played.append(hm)

    if hm > 0:
        home_win_rate.append(home_stats["wins"] / hm)
        home_draw_rate.append(home_stats["draws"] / hm)
        home_loss_rate.append(home_stats["losses"] / hm)

        home_avg_goals_scored.append(
            home_stats["goals_scored"] / hm
        )

        home_avg_goals_conceded.append(
            home_stats["goals_conceded"] / hm
        )

    else:
        home_win_rate.append(0)
        home_draw_rate.append(0)
        home_loss_rate.append(0)

        home_avg_goals_scored.append(0)
        home_avg_goals_conceded.append(0)

    # AWAY TEAM FEATURES
    am = away_stats["matches"]

    away_matches_played.append(am)

    if am > 0:
        away_win_rate.append(away_stats["wins"] / am)
        away_draw_rate.append(away_stats["draws"] / am)
        away_loss_rate.append(away_stats["losses"] / am)

        away_avg_goals_scored.append(
            away_stats["goals_scored"] / am
        )

        away_avg_goals_conceded.append(
            away_stats["goals_conceded"] / am
        )

    else:
        away_win_rate.append(0)
        away_draw_rate.append(0)
        away_loss_rate.append(0)

        away_avg_goals_scored.append(0)
        away_avg_goals_conceded.append(0)

    # UPDATE TEAM STATS AFTER FEATURE CREATION
    home_score = row["home_score"]
    away_score = row["away_score"]

    # Matches played

    team_stats[home]["matches"] += 1
    team_stats[away]["matches"] += 1

    # Goals

    team_stats[home]["goals_scored"] += home_score
    team_stats[home]["goals_conceded"] += away_score

    team_stats[away]["goals_scored"] += away_score
    team_stats[away]["goals_conceded"] += home_score

    # Results

    if home_score > away_score:

        team_stats[home]["wins"] += 1
        team_stats[away]["losses"] += 1

    elif home_score < away_score:

        team_stats[away]["wins"] += 1
        team_stats[home]["losses"] += 1

    else:

        team_stats[home]["draws"] += 1
        team_stats[away]["draws"] += 1

In [5]:
df["home_matches_played"] = home_matches_played
df["away_matches_played"] = away_matches_played

df["home_win_rate"] = home_win_rate
df["away_win_rate"] = away_win_rate

df["home_draw_rate"] = home_draw_rate
df["away_draw_rate"] = away_draw_rate

df["home_loss_rate"] = home_loss_rate
df["away_loss_rate"] = away_loss_rate

df["home_avg_goals_scored"] = home_avg_goals_scored
df["away_avg_goals_scored"] = away_avg_goals_scored

df["home_avg_goals_conceded"] = home_avg_goals_conceded
df["away_avg_goals_conceded"] = away_avg_goals_conceded
#First matches for all team has 0 avg

In [6]:
df["win_rate_diff"] = (
    df["home_win_rate"]
    - df["away_win_rate"]
)

df["draw_rate_diff"] = (
    df["home_draw_rate"]
    - df["away_draw_rate"]
)

df["loss_rate_diff"] = (
    df["home_loss_rate"]
    - df["away_loss_rate"]
)

df["goals_scored_diff"] = (
    df["home_avg_goals_scored"]
    - df["away_avg_goals_scored"]
)

df["goals_conceded_diff"] = (
    df["home_avg_goals_conceded"]
    - df["away_avg_goals_conceded"]
)

df["matches_played_diff"] = (
    df["home_matches_played"]
    - df["away_matches_played"]
)
df

,date,home_team,away_team,home_score,away_score,tournament,city,country,neutral,year,...,home_avg_goals_scored,away_avg_goals_scored,home_avg_goals_conceded,away_avg_goals_conceded,win_rate_diff,draw_rate_diff,loss_rate_diff,goals_scored_diff,goals_conceded_diff,matches_played_diff
0,2000-01-04,Egypt,Togo,2.0,1.0,Friendly,Aswan,Egypt,False,2000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0
1,2000-01-07,Tunisia,Togo,7.0,0.0,Friendly,Tunis,Tunisia,False,2000,...,0.000000,1.000000,0.000000,2.000000,0.000000,0.000000,-1.000000,-1.000000,-2.000000,-1
2,2000-01-08,Trinidad and Tobago,Canada,0.0,0.0,Friendly,Port of Spain,Trinidad and Tobago,False,2000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0
3,2000-01-09,Burkina Faso,Gabon,1.0,1.0,Friendly,Ouagadougou,Burkina Faso,False,2000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0
4,2000-01-09,Guatemala,Armenia,1.0,1.0,Friendly,Los Angeles,United States,True,2000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25237,2026-06-03,Gibraltar,British Virgin Islands,4.0,0.0,Friendly,Gibraltar,Gibraltar,False,2026,...,1.014493,0.935484,2.630435,2.978495,0.056101,-0.059374,0.003273,0.079009,-0.348060,45
25236,2026-06-03,DR Congo,Denmark,0.0,0.0,Friendly,Liège,Belgium,True,2026,...,1.329545,1.673611,1.121212,0.996528,-0.121843,0.053662,0.068182,-0.344066,0.124684,-24
25235,2026-06-03,Albania,Israel,0.0,1.0,Friendly,Tirana,Albania,False,2026,...,1.069106,1.536697,1.174797,1.495413,-0.035728,-0.010368,0.046095,-0.467592,-0.320616,28
25238,2026-06-03,South Korea,El Salvador,1.0,0.0,Friendly,Provo,United States,True,2026,...,1.595477,1.103896,0.904523,1.370130,0.188312,0.032565,-0.220877,0.491581,-0.465607,90
25243,2026-06-03,Philippines,Guam,5.0,1.0,Friendly,Manila,Philippines,False,2026,...,1.331754,1.042553,1.601896,4.042553,0.143844,0.105728,-0.249571,0.289200,-2.440657,117

In [7]:
feature_cols = [
    "home_win_rate",
    "away_win_rate",
    "home_avg_goals_scored",
    "away_avg_goals_scored",
    "win_rate_diff",
]

df[feature_cols].tail(20)

,home_win_rate,away_win_rate,home_avg_goals_scored,away_avg_goals_scored,win_rate_diff
25226,0.448029,0.477876,1.487455,1.610619,-0.029847
25229,0.302198,0.276423,1.335165,1.040650,0.025775
25224,0.421260,0.472414,1.452756,1.600000,-0.051154
25223,0.356275,0.339394,1.186235,1.187879,0.016881
25222,0.423529,0.470414,1.525490,1.505917,-0.046885
25225,0.473520,0.400504,1.367601,1.408060,0.073016
25232,0.403922,0.405714,1.698039,1.577143,-0.001793
25233,0.554098,0.300518,1.573770,1.093264,0.253580
25230,0.531353,0.549296,1.689769,1.978873,-0.017943
25231,0.315789,0.465950,1.210526,1.530466,-0.150160
25234,0.377593,0.436482,1.170124,1.423453,-0.058889
25240,0.603774,0.511628,2.103774,1.700997,0.092146
25241,0.372222,0.427419,1.261111,1.846774,-0.055197
25239,0.142857,0.533742,0.634454,1.638037,-0.390885
25242,0.470588,0.503106,1.653251,1.518634,-0.032517
25237,0.217391,0.161290,1.014493,0.935484,0.056101
25236,0.371212,0.493056,1.329545,1.673611,-0.121843
25235,0.349593,0.385321,1.069106,1.536697,-0.035728
25238,0.500000,0.311688,1.595477,1.103896,0.188312
25243,0.345972,0.202128,1.331754,1.042553,0.143844

# Recent Form

In [8]:
from collections import defaultdict, deque

recent_results = defaultdict(lambda: deque(maxlen=5))
recent_goals_scored = defaultdict(lambda: deque(maxlen=5))
recent_goals_conceded = defaultdict(lambda: deque(maxlen=5))

# Feature lists

home_last5_win_rate = []
away_last5_win_rate = []

home_last5_avg_goals_scored = []
away_last5_avg_goals_scored = []

home_last5_avg_goals_conceded = []
away_last5_avg_goals_conceded = []

In [9]:
for _, row in df.iterrows():

    home = row["home_team"]
    away = row["away_team"]

    # HOME TEAM FEATURES
    if len(recent_results[home]) > 0:

        home_last5_win_rate.append(
            sum(recent_results[home]) / len(recent_results[home])
        )

        home_last5_avg_goals_scored.append(
            sum(recent_goals_scored[home])
            / len(recent_goals_scored[home])
        )

        home_last5_avg_goals_conceded.append(
            sum(recent_goals_conceded[home])
            / len(recent_goals_conceded[home])
        )

    else:

        home_last5_win_rate.append(0)
        home_last5_avg_goals_scored.append(0)
        home_last5_avg_goals_conceded.append(0)

    # AWAY TEAM FEATURES
    if len(recent_results[away]) > 0:

        away_last5_win_rate.append(
            sum(recent_results[away]) / len(recent_results[away])
        )

        away_last5_avg_goals_scored.append(
            sum(recent_goals_scored[away])
            / len(recent_goals_scored[away])
        )

        away_last5_avg_goals_conceded.append(
            sum(recent_goals_conceded[away])
            / len(recent_goals_conceded[away])
        )

    else:

        away_last5_win_rate.append(0)
        away_last5_avg_goals_scored.append(0)
        away_last5_avg_goals_conceded.append(0)
    
    # UPDATE HISTORY AFTER FEATURE CREATION
    home_score = row["home_score"]
    away_score = row["away_score"]

    # Match result encoding
    # Win = 1
    # Draw = 0.5
    # Loss = 0

    if home_score > away_score:

        recent_results[home].append(1)
        recent_results[away].append(0)

    elif home_score < away_score:

        recent_results[home].append(0)
        recent_results[away].append(1)

    else:

        recent_results[home].append(0.5)
        recent_results[away].append(0.5)

    # Goals

    recent_goals_scored[home].append(home_score)
    recent_goals_conceded[home].append(away_score)

    recent_goals_scored[away].append(away_score)
    recent_goals_conceded[away].append(home_score)

In [10]:
df["home_last5_win_rate"] = home_last5_win_rate
df["away_last5_win_rate"] = away_last5_win_rate

df["home_last5_avg_goals_scored"] = (
    home_last5_avg_goals_scored
)

df["away_last5_avg_goals_scored"] = (
    away_last5_avg_goals_scored
)

df["home_last5_avg_goals_conceded"] = (
    home_last5_avg_goals_conceded
)

df["away_last5_avg_goals_conceded"] = (
    away_last5_avg_goals_conceded
)

In [11]:
df["last5_win_rate_diff"] = (
    df["home_last5_win_rate"]
    - df["away_last5_win_rate"]
)

df["last5_goals_scored_diff"] = (
    df["home_last5_avg_goals_scored"]
    - df["away_last5_avg_goals_scored"]
)

df["last5_goals_conceded_diff"] = (
    df["home_last5_avg_goals_conceded"]
    - df["away_last5_avg_goals_conceded"]
)

In [12]:
recent_cols = [
    "home_last5_win_rate",
    "away_last5_win_rate",
    "last5_win_rate_diff"
]

df[recent_cols].tail(20)

       home_last5_win_rate  away_last5_win_rate  last5_win_rate_diff
25226                  0.6                  0.5                  0.1
25229                  0.3                  0.2                  0.1
25224                  0.6                  0.7                 -0.1
25223                  0.6                  0.6                  0.0
25222                  0.7                  0.5                  0.2
25225                  0.5                  0.4                  0.1
25232                  0.5                  0.3                  0.2
25233                  0.8                  0.7                  0.1
25230                  0.8                  0.8                  0.0
25231                  0.3                  0.4                 -0.1
25234                  0.6                  0.0                  0.6
25240                  0.8                  0.7                  0.1
25241                  0.4                  0.5                 -0.1
25239                  0.0                  0.7                 -0.7
25242                  0.5                  0.8                 -0.3
25237                  0.0                  0.7                 -0.7
25236                  0.7                  0.6                  0.1
25235                  0.4                  0.4                  0.0
25238                  0.6                  0.3                  0.3
25243                  0.9                  0.4                  0.5

In [13]:
df.to_csv("../data/processed/features_v1.csv",
            index=True)

# H2H features

In [14]:
from collections import defaultdict

h2h_stats = defaultdict(
    lambda: {
        "matches": 0,
        "team1_wins": 0,
        "team2_wins": 0,
        "draws": 0
    }
)

h2h_matches = []
h2h_home_win_rate = []
h2h_away_win_rate = []
h2h_draw_rate = []

In [15]:
for _, row in df.iterrows():

    home = row["home_team"]
    away = row["away_team"]

    # Create a consistent key
    teams = tuple(sorted([home, away]))

    stats = h2h_stats[teams]

    matches = stats["matches"]

    if matches > 0:

        if home == teams[0]:

            home_wins = stats["team1_wins"]
            away_wins = stats["team2_wins"]

        else:

            home_wins = stats["team2_wins"]
            away_wins = stats["team1_wins"]

        h2h_matches.append(matches)

        h2h_home_win_rate.append(
            home_wins / matches
        )

        h2h_away_win_rate.append(
            away_wins / matches
        )

        h2h_draw_rate.append(
            stats["draws"] / matches
        )

    else:

        h2h_matches.append(0)
        h2h_home_win_rate.append(0)
        h2h_away_win_rate.append(0)
        h2h_draw_rate.append(0)

    # Update after feature creation

    home_score = row["home_score"]
    away_score = row["away_score"]

    stats["matches"] += 1

    if home_score > away_score:

        if home == teams[0]:
            stats["team1_wins"] += 1
        else:
            stats["team2_wins"] += 1

    elif home_score < away_score:

        if away == teams[0]:
            stats["team1_wins"] += 1
        else:
            stats["team2_wins"] += 1

    else:

        stats["draws"] += 1

In [16]:
df["h2h_matches"] = h2h_matches

df["h2h_home_win_rate"] = h2h_home_win_rate
df["h2h_away_win_rate"] = h2h_away_win_rate
df["h2h_draw_rate"] = h2h_draw_rate

In [17]:
df["h2h_win_rate_diff"] = (
    df["h2h_home_win_rate"]
    - df["h2h_away_win_rate"]
)

In [18]:
cols = [
    "home_team",
    "away_team",
    "h2h_matches",
    "h2h_home_win_rate",
    "h2h_away_win_rate"
]

df[cols].sample(10)

,home_team,away_team,h2h_matches,h2h_home_win_rate,h2h_away_win_rate
4742,Saudi Arabia,Sri Lanka,1,1.000000,0.000000
7956,Botswana,Ivory Coast,0,0.000000,0.000000
25067,Italy,Northern Ireland,6,0.666667,0.000000
17916,Belarus,Moldova,7,0.285714,0.285714
6557,Cuba,Guadeloupe,2,0.500000,0.500000
510,United States,South Africa,0,0.000000,0.000000
19635,Tanzania,Tunisia,1,0.000000,1.000000
19095,Thailand,United Arab Emirates,6,0.166667,0.333333
975,Thailand,Philippines,0,0.000000,0.000000
12792,Costa Rica,Jamaica,7,0.428571,0.142857

# Tournament Features

In [19]:
def categorize_tournament(tournament):

    tournament = str(tournament)

    if tournament == "FIFA World Cup":
        return "world_cup"

    elif "World Cup qualification" in tournament:
        return "world_cup_qualifier"

    elif tournament in [
        "UEFA Euro",
        "Copa América",
        "African Cup of Nations",
        "AFC Asian Cup",
        "CONCACAF Gold Cup"
    ]:
        return "continental_championship"

    elif "Nations League" in tournament:
        return "nations_league"

    elif tournament == "Friendly":
        return "friendly"

    else:
        return "other"

In [20]:
df["tournament_category"] = df["tournament"].apply(
    categorize_tournament
)
df.sample(10)

,date,home_team,away_team,home_score,away_score,tournament,city,country,neutral,year,...,away_last5_avg_goals_conceded,last5_win_rate_diff,last5_goals_scored_diff,last5_goals_conceded_diff,h2h_matches,h2h_home_win_rate,h2h_away_win_rate,h2h_draw_rate,h2h_win_rate_diff,tournament_category
5431,2005-09-07,Japan,Honduras,5.0,4.0,Friendly,Rifu,Japan,False,2005,...,1.20,-0.1,-0.20,0.00,1,0.00,0.000000,1.000000,0.000000,friendly
97,2000-02-10,Cameroon,Tunisia,3.0,0.0,African Cup of Nations,Accra,Ghana,True,2000,...,1.20,0.1,0.40,-0.60,0,0.00,0.000000,0.000000,0.000000,continental_championship
8863,2009-04-14,Mongolia,Macau,3.0,1.0,AFC Challenge Cup qualification,Ulaanbaatar,Mongolia,False,2009,...,2.80,-0.1,-1.00,-0.80,4,0.25,0.500000,0.250000,-0.250000,other
794,2000-09-02,Switzerland,Russia,0.0,1.0,FIFA World Cup qualification,Zürich,Switzerland,False,2000,...,1.00,-0.2,0.60,0.40,0,0.00,0.000000,0.000000,0.000000,world_cup_qualifier
6537,2007-01-16,Guadeloupe,Guyana,3.0,4.0,CFU Caribbean Cup,San Fernando,Trinidad and Tobago,True,2007,...,0.40,-0.4,-1.80,1.20,1,0.00,1.000000,0.000000,-1.000000,other
15944,2016-09-02,Haiti,Costa Rica,0.0,1.0,FIFA World Cup qualification,Port-au-Prince,Haiti,False,2016,...,1.40,-0.6,-1.40,1.20,7,0.00,0.571429,0.428571,-0.571429,world_cup_qualifier
1261,2001-03-24,British Virgin Islands,United States Virgin Islands,2.0,0.0,Friendly,Road Town,British Virgin Islands,False,2001,...,6.25,0.6,0.55,-5.65,0,0.00,0.000000,0.000000,0.000000,friendly
20353,2021-09-07,Ethiopia,Zimbabwe,1.0,0.0,FIFA World Cup qualification,Bahir Dar,Ethiopia,False,2021,...,1.20,0.2,0.80,-0.20,0,0.00,0.000000,0.000000,0.000000,world_cup_qualifier
9401,2009-11-13,Paraguay,Qatar,0.0,2.0,Friendly,Rouen,France,True,2009,...,1.80,0.3,-0.40,-0.80,0,0.00,0.000000,0.000000,0.000000,friendly
4264,2004-06-18,Bulgaria,Denmark,0.0,2.0,UEFA Euro,Braga,Portugal,True,2004,...,1.20,-0.1,0.40,1.20,2,0.00,0.500000,0.500000,-0.500000,continental_championship

In [21]:
df["tournament_category"].value_counts()

tournament_category
friendly                    8361
other                       8204
world_cup_qualifier         5841
continental_championship    1306
nations_league              1148
world_cup                    384
Name: count, dtype: int64

In [22]:
tournament_dummies = pd.get_dummies(
    df["tournament_category"],
    prefix="tournament"
)

df = pd.concat(
    [df, tournament_dummies],
    axis=1
)

In [23]:
df["neutral"] = df["neutral"].astype(int)

In [24]:
df.to_csv(
    "../data/processed/features_v1.csv",
    index=False
)

print("features_v1.csv saved successfully")

features_v1.csv saved successfully

In [25]:
# Absolute difference features

df["abs_win_rate_diff"] = abs(df["win_rate_diff"])

df["abs_last5_diff"] = abs(df["last5_win_rate_diff"])

df["abs_h2h_diff"] = abs(df["h2h_win_rate_diff"])

df["abs_goals_scored_diff"] = abs(df["goals_scored_diff"])

df["abs_goals_conceded_diff"] = abs(df["goals_conceded_diff"])

In [26]:
# Strength gap

df["strength_gap"] = (
    abs(df["home_win_rate"] - df["away_win_rate"])
    +
    abs(df["home_last5_win_rate"] - df["away_last5_win_rate"])
)

In [27]:
# Goal balance

df["home_goal_balance"] = (
    df["home_avg_goals_scored"]
    - df["home_avg_goals_conceded"]
)

df["away_goal_balance"] = (
    df["away_avg_goals_scored"]
    - df["away_avg_goals_conceded"]
)

df["goal_balance_diff"] = (
    df["home_goal_balance"]
    - df["away_goal_balance"]
)

In [28]:
df.to_csv(
    "../data/processed/features_v2.csv",
    index=False
)

# Elo Rating

In [29]:
from collections import defaultdict

INITIAL_ELO = 1500
K = 20

elo_ratings = defaultdict(lambda: INITIAL_ELO)

home_elo = []
away_elo = []
elo_diff = []

In [30]:
for _, row in df.iterrows():

    home = row["home_team"]
    away = row["away_team"]

    home_rating = elo_ratings[home]
    away_rating = elo_ratings[away]

    # Features BEFORE update
    home_elo.append(home_rating)
    away_elo.append(away_rating)
    elo_diff.append(home_rating - away_rating)

    # Actual result
    home_score = row["home_score"]
    away_score = row["away_score"]

    if home_score > away_score:
        actual_home = 1
        actual_away = 0

    elif home_score < away_score:
        actual_home = 0
        actual_away = 1

    else:
        actual_home = 0.5
        actual_away = 0.5

    # Expected result
    expected_home = 1 / (
        1 + 10 ** ((away_rating - home_rating) / 400)
    )

    expected_away = 1 - expected_home

    # Update ratings
    elo_ratings[home] += K * (
        actual_home - expected_home
    )

    elo_ratings[away] += K * (
        actual_away - expected_away
    )

In [31]:
df["home_elo"] = home_elo
df["away_elo"] = away_elo

df["elo_diff"] = elo_diff

In [32]:
df[
    [
        "home_team",
        "away_team",
        "home_elo",
        "away_elo",
        "elo_diff"
    ]
].head(20)

,home_team,away_team,home_elo,away_elo,elo_diff
0,Egypt,Togo,1500.000000,1500.000000,0.000000
1,Tunisia,Togo,1500.000000,1490.000000,10.000000
2,Trinidad and Tobago,Canada,1500.000000,1500.000000,0.000000
3,Burkina Faso,Gabon,1500.000000,1500.000000,0.000000
4,Guatemala,Armenia,1500.000000,1500.000000,0.000000
5,Ivory Coast,Egypt,1500.000000,1510.000000,-10.000000
6,Mexico,Iran,1500.000000,1500.000000,0.000000
7,Bermuda,Canada,1500.000000,1500.000000,0.000000
8,Burkina Faso,Cameroon,1500.000000,1500.000000,0.000000
9,Senegal,Cameroon,1500.000000,1500.000000,0.000000
10,China PR,New Zealand,1500.000000,1500.000000,0.000000
12,United States,Iran,1500.000000,1490.000000,10.000000
11,Jamaica,New Zealand,1500.000000,1490.000000,10.000000
13,Ghana,Tunisia,1500.000000,1509.712256,-9.712256
14,Morocco,Trinidad and Tobago,1500.000000,1500.000000,0.000000
15,Panama,Guatemala,1500.000000,1500.000000,0.000000
16,Togo,Egypt,1480.287744,1499.712256,-19.424513
17,Burkina Faso,Algeria,1500.000000,1500.000000,0.000000
18,Malta,Qatar,1500.000000,1500.000000,0.000000
19,New Zealand,South Korea,1480.287744,1500.000000,-19.712256

In [33]:
df.to_csv(
    "../data/processed/features_v3.csv",
    index=False
)