In [2]:
import pandas as pd

df = pd.read_csv("../data/processed/cleaned_matches.csv")
df["date"] = pd.to_datetime(df["date"])

df = df.sort_values("date")
df.head()

,date,home_team,away_team,home_score,away_score,tournament,city,country,neutral,year,month,result
0,2000-01-04,Egypt,Togo,2.0,1.0,Friendly,Aswan,Egypt,False,2000,1,Home Win
1,2000-01-07,Tunisia,Togo,7.0,0.0,Friendly,Tunis,Tunisia,False,2000,1,Home Win
2,2000-01-08,Trinidad and Tobago,Canada,0.0,0.0,Friendly,Port of Spain,Trinidad and Tobago,False,2000,1,Draw
3,2000-01-09,Burkina Faso,Gabon,1.0,1.0,Friendly,Ouagadougou,Burkina Faso,False,2000,1,Draw
4,2000-01-09,Guatemala,Armenia,1.0,1.0,Friendly,Los Angeles,United States,True,2000,1,Draw

In [4]:
# Store historical team statistics
from collections import defaultdict
team_stats = defaultdict(
    lambda: {
        "matches": 0,
        "wins": 0,
        "draws": 0,
        "losses": 0,
        "goals_scored": 0,
        "goals_conceded": 0,
    }
)

# Feature storage
home_matches_played = []
away_matches_played = []

home_win_rate = []
away_win_rate = []

home_draw_rate = []
away_draw_rate = []

home_loss_rate = []
away_loss_rate = []

home_avg_goals_scored = []
away_avg_goals_scored = []

home_avg_goals_conceded = []
away_avg_goals_conceded = []

In [5]:
for _, row in df.iterrows():

    home = row["home_team"]
    away = row["away_team"]

    home_stats = team_stats[home]
    away_stats = team_stats[away]


    # HOME TEAM FEATURES
    hm = home_stats["matches"]

    home_matches_played.append(hm)

    if hm > 0:
        home_win_rate.append(home_stats["wins"] / hm)
        home_draw_rate.append(home_stats["draws"] / hm)
        home_loss_rate.append(home_stats["losses"] / hm)

        home_avg_goals_scored.append(
            home_stats["goals_scored"] / hm
        )

        home_avg_goals_conceded.append(
            home_stats["goals_conceded"] / hm
        )

    else:
        home_win_rate.append(0)
        home_draw_rate.append(0)
        home_loss_rate.append(0)

        home_avg_goals_scored.append(0)
        home_avg_goals_conceded.append(0)

    # AWAY TEAM FEATURES
    am = away_stats["matches"]

    away_matches_played.append(am)

    if am > 0:
        away_win_rate.append(away_stats["wins"] / am)
        away_draw_rate.append(away_stats["draws"] / am)
        away_loss_rate.append(away_stats["losses"] / am)

        away_avg_goals_scored.append(
            away_stats["goals_scored"] / am
        )

        away_avg_goals_conceded.append(
            away_stats["goals_conceded"] / am
        )

    else:
        away_win_rate.append(0)
        away_draw_rate.append(0)
        away_loss_rate.append(0)

        away_avg_goals_scored.append(0)
        away_avg_goals_conceded.append(0)

    # UPDATE TEAM STATS AFTER FEATURE CREATION
    home_score = row["home_score"]
    away_score = row["away_score"]

    # Matches played

    team_stats[home]["matches"] += 1
    team_stats[away]["matches"] += 1

    # Goals

    team_stats[home]["goals_scored"] += home_score
    team_stats[home]["goals_conceded"] += away_score

    team_stats[away]["goals_scored"] += away_score
    team_stats[away]["goals_conceded"] += home_score

    # Results

    if home_score > away_score:

        team_stats[home]["wins"] += 1
        team_stats[away]["losses"] += 1

    elif home_score < away_score:

        team_stats[away]["wins"] += 1
        team_stats[home]["losses"] += 1

    else:

        team_stats[home]["draws"] += 1
        team_stats[away]["draws"] += 1

In [ ]:
df["home_matches_played"] = home_matches_played
df["away_matches_played"] = away_matches_played

df["home_win_rate"] = home_win_rate
df["away_win_rate"] = away_win_rate

df["home_draw_rate"] = home_draw_rate
df["away_draw_rate"] = away_draw_rate

df["home_loss_rate"] = home_loss_rate
df["away_loss_rate"] = away_loss_rate

df["home_avg_goals_scored"] = home_avg_goals_scored
df["away_avg_goals_scored"] = away_avg_goals_scored

df["home_avg_goals_conceded"] = home_avg_goals_conceded
df["away_avg_goals_conceded"] = away_avg_goals_conceded
#First matches for all team has 0 avg

In [10]:
df["win_rate_diff"] = (
    df["home_win_rate"]
    - df["away_win_rate"]
)

df["draw_rate_diff"] = (
    df["home_draw_rate"]
    - df["away_draw_rate"]
)

df["loss_rate_diff"] = (
    df["home_loss_rate"]
    - df["away_loss_rate"]
)

df["goals_scored_diff"] = (
    df["home_avg_goals_scored"]
    - df["away_avg_goals_scored"]
)

df["goals_conceded_diff"] = (
    df["home_avg_goals_conceded"]
    - df["away_avg_goals_conceded"]
)

df["matches_played_diff"] = (
    df["home_matches_played"]
    - df["away_matches_played"]
)
df

,date,home_team,away_team,home_score,away_score,tournament,city,country,neutral,year,...,home_avg_goals_scored,away_avg_goals_scored,home_avg_goals_conceded,away_avg_goals_conceded,win_rate_diff,draw_rate_diff,loss_rate_diff,goals_scored_diff,goals_conceded_diff,matches_played_diff
0,2000-01-04,Egypt,Togo,2.0,1.0,Friendly,Aswan,Egypt,False,2000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0
1,2000-01-07,Tunisia,Togo,7.0,0.0,Friendly,Tunis,Tunisia,False,2000,...,0.000000,1.000000,0.000000,2.000000,0.000000,0.000000,-1.000000,-1.000000,-2.000000,-1
2,2000-01-08,Trinidad and Tobago,Canada,0.0,0.0,Friendly,Port of Spain,Trinidad and Tobago,False,2000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0
3,2000-01-09,Burkina Faso,Gabon,1.0,1.0,Friendly,Ouagadougou,Burkina Faso,False,2000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0
4,2000-01-09,Guatemala,Armenia,1.0,1.0,Friendly,Los Angeles,United States,True,2000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25237,2026-06-03,Gibraltar,British Virgin Islands,4.0,0.0,Friendly,Gibraltar,Gibraltar,False,2026,...,1.014493,0.935484,2.630435,2.978495,0.056101,-0.059374,0.003273,0.079009,-0.348060,45
25236,2026-06-03,DR Congo,Denmark,0.0,0.0,Friendly,Liège,Belgium,True,2026,...,1.329545,1.673611,1.121212,0.996528,-0.121843,0.053662,0.068182,-0.344066,0.124684,-24
25235,2026-06-03,Albania,Israel,0.0,1.0,Friendly,Tirana,Albania,False,2026,...,1.069106,1.536697,1.174797,1.495413,-0.035728,-0.010368,0.046095,-0.467592,-0.320616,28
25238,2026-06-03,South Korea,El Salvador,1.0,0.0,Friendly,Provo,United States,True,2026,...,1.595477,1.103896,0.904523,1.370130,0.188312,0.032565,-0.220877,0.491581,-0.465607,90
25243,2026-06-03,Philippines,Guam,5.0,1.0,Friendly,Manila,Philippines,False,2026,...,1.331754,1.042553,1.601896,4.042553,0.143844,0.105728,-0.249571,0.289200,-2.440657,117

In [12]:
feature_cols = [
    "home_win_rate",
    "away_win_rate",
    "home_avg_goals_scored",
    "away_avg_goals_scored",
    "win_rate_diff",
]

df[feature_cols].tail(20)

,home_win_rate,away_win_rate,home_avg_goals_scored,away_avg_goals_scored,win_rate_diff
25226,0.448029,0.477876,1.487455,1.610619,-0.029847
25229,0.302198,0.276423,1.335165,1.040650,0.025775
25224,0.421260,0.472414,1.452756,1.600000,-0.051154
25223,0.356275,0.339394,1.186235,1.187879,0.016881
25222,0.423529,0.470414,1.525490,1.505917,-0.046885
25225,0.473520,0.400504,1.367601,1.408060,0.073016
25232,0.403922,0.405714,1.698039,1.577143,-0.001793
25233,0.554098,0.300518,1.573770,1.093264,0.253580
25230,0.531353,0.549296,1.689769,1.978873,-0.017943
25231,0.315789,0.465950,1.210526,1.530466,-0.150160
25234,0.377593,0.436482,1.170124,1.423453,-0.058889
25240,0.603774,0.511628,2.103774,1.700997,0.092146
25241,0.372222,0.427419,1.261111,1.846774,-0.055197
25239,0.142857,0.533742,0.634454,1.638037,-0.390885
25242,0.470588,0.503106,1.653251,1.518634,-0.032517
25237,0.217391,0.161290,1.014493,0.935484,0.056101
25236,0.371212,0.493056,1.329545,1.673611,-0.121843
25235,0.349593,0.385321,1.069106,1.536697,-0.035728
25238,0.500000,0.311688,1.595477,1.103896,0.188312
25243,0.345972,0.202128,1.331754,1.042553,0.143844

In [13]:
df.to_csv("../data/processed/features_v1.csv",
            index=True)

# Recent Form

In [14]:
from collections import defaultdict, deque

recent_results = defaultdict(lambda: deque(maxlen=5))
recent_goals_scored = defaultdict(lambda: deque(maxlen=5))
recent_goals_conceded = defaultdict(lambda: deque(maxlen=5))

# Feature lists

home_last5_win_rate = []
away_last5_win_rate = []

home_last5_avg_goals_scored = []
away_last5_avg_goals_scored = []

home_last5_avg_goals_conceded = []
away_last5_avg_goals_conceded = []

In [15]:
for _, row in df.iterrows():

    home = row["home_team"]
    away = row["away_team"]

    # HOME TEAM FEATURES
    if len(recent_results[home]) > 0:

        home_last5_win_rate.append(
            sum(recent_results[home]) / len(recent_results[home])
        )

        home_last5_avg_goals_scored.append(
            sum(recent_goals_scored[home])
            / len(recent_goals_scored[home])
        )

        home_last5_avg_goals_conceded.append(
            sum(recent_goals_conceded[home])
            / len(recent_goals_conceded[home])
        )

    else:

        home_last5_win_rate.append(0)
        home_last5_avg_goals_scored.append(0)
        home_last5_avg_goals_conceded.append(0)

    # AWAY TEAM FEATURES
    if len(recent_results[away]) > 0:

        away_last5_win_rate.append(
            sum(recent_results[away]) / len(recent_results[away])
        )

        away_last5_avg_goals_scored.append(
            sum(recent_goals_scored[away])
            / len(recent_goals_scored[away])
        )

        away_last5_avg_goals_conceded.append(
            sum(recent_goals_conceded[away])
            / len(recent_goals_conceded[away])
        )

    else:

        away_last5_win_rate.append(0)
        away_last5_avg_goals_scored.append(0)
        away_last5_avg_goals_conceded.append(0)
    
    # UPDATE HISTORY AFTER FEATURE CREATION
    home_score = row["home_score"]
    away_score = row["away_score"]

    # Match result encoding
    # Win = 1
    # Draw = 0.5
    # Loss = 0

    if home_score > away_score:

        recent_results[home].append(1)
        recent_results[away].append(0)

    elif home_score < away_score:

        recent_results[home].append(0)
        recent_results[away].append(1)

    else:

        recent_results[home].append(0.5)
        recent_results[away].append(0.5)

    # Goals

    recent_goals_scored[home].append(home_score)
    recent_goals_conceded[home].append(away_score)

    recent_goals_scored[away].append(away_score)
    recent_goals_conceded[away].append(home_score)

In [16]:
df["home_last5_win_rate"] = home_last5_win_rate
df["away_last5_win_rate"] = away_last5_win_rate

df["home_last5_avg_goals_scored"] = (
    home_last5_avg_goals_scored
)

df["away_last5_avg_goals_scored"] = (
    away_last5_avg_goals_scored
)

df["home_last5_avg_goals_conceded"] = (
    home_last5_avg_goals_conceded
)

df["away_last5_avg_goals_conceded"] = (
    away_last5_avg_goals_conceded
)

In [17]:
df["last5_win_rate_diff"] = (
    df["home_last5_win_rate"]
    - df["away_last5_win_rate"]
)

df["last5_goals_scored_diff"] = (
    df["home_last5_avg_goals_scored"]
    - df["away_last5_avg_goals_scored"]
)

df["last5_goals_conceded_diff"] = (
    df["home_last5_avg_goals_conceded"]
    - df["away_last5_avg_goals_conceded"]
)

In [19]:
recent_cols = [
    "home_last5_win_rate",
    "away_last5_win_rate",
    "last5_win_rate_diff"
]

df[recent_cols].tail(20)

       home_last5_win_rate  away_last5_win_rate  last5_win_rate_diff
25226                  0.6                  0.5                  0.1
25229                  0.3                  0.2                  0.1
25224                  0.6                  0.7                 -0.1
25223                  0.6                  0.6                  0.0
25222                  0.7                  0.5                  0.2
25225                  0.5                  0.4                  0.1
25232                  0.5                  0.3                  0.2
25233                  0.8                  0.7                  0.1
25230                  0.8                  0.8                  0.0
25231                  0.3                  0.4                 -0.1
25234                  0.6                  0.0                  0.6
25240                  0.8                  0.7                  0.1
25241                  0.4                  0.5                 -0.1
25239                  0.0                  0.7                 -0.7
25242                  0.5                  0.8                 -0.3
25237                  0.0                  0.7                 -0.7
25236                  0.7                  0.6                  0.1
25235                  0.4                  0.4                  0.0
25238                  0.6                  0.3                  0.3
25243                  0.9                  0.4                  0.5