In [74]:
import pandas as pd 
import numpy as np 

from sklearn.model_selection import train_test_split

from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import (accuracy_score,classification_report,confusion_matrix)

import joblib

In [75]:
df = pd.read_csv("../data/processed/features_v3.csv")

print(df.shape)
df.head()

(25244, 63)

,date,home_team,away_team,home_score,away_score,tournament,city,country,neutral,year,...,abs_h2h_diff,abs_goals_scored_diff,abs_goals_conceded_diff,strength_gap,home_goal_balance,away_goal_balance,goal_balance_diff,home_elo,away_elo,elo_diff
0,2000-01-04,Egypt,Togo,2.0,1.0,Friendly,Aswan,Egypt,0,2000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1500.0,1500.0,0.0
1,2000-01-07,Tunisia,Togo,7.0,0.0,Friendly,Tunis,Tunisia,0,2000,...,0.0,1.0,2.0,0.0,0.0,-1.0,1.0,1500.0,1490.0,10.0
2,2000-01-08,Trinidad and Tobago,Canada,0.0,0.0,Friendly,Port of Spain,Trinidad and Tobago,0,2000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1500.0,1500.0,0.0
3,2000-01-09,Burkina Faso,Gabon,1.0,1.0,Friendly,Ouagadougou,Burkina Faso,0,2000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1500.0,1500.0,0.0
4,2000-01-09,Guatemala,Armenia,1.0,1.0,Friendly,Los Angeles,United States,1,2000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1500.0,1500.0,0.0

In [76]:
new_cols = [
    "abs_win_rate_diff",
    "abs_last5_diff",
    "abs_h2h_diff",
    "abs_goals_scored_diff",
    "abs_goals_conceded_diff",
    "strength_gap",
    "home_goal_balance",
    "away_goal_balance",
    "goal_balance_diff"
]

df[new_cols].head()

,abs_win_rate_diff,abs_last5_diff,abs_h2h_diff,abs_goals_scored_diff,abs_goals_conceded_diff,strength_gap,home_goal_balance,away_goal_balance,goal_balance_diff
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.0,0.0,0.0,1.0,2.0,0.0,0.0,-1.0,1.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [77]:
df.columns.tolist()

['date',
 'home_team',
 'away_team',
 'home_score',
 'away_score',
 'tournament',
 'city',
 'country',
 'neutral',
 'year',
 'month',
 'result',
 'home_matches_played',
 'away_matches_played',
 'home_win_rate',
 'away_win_rate',
 'home_draw_rate',
 'away_draw_rate',
 'home_loss_rate',
 'away_loss_rate',
 'home_avg_goals_scored',
 'away_avg_goals_scored',
 'home_avg_goals_conceded',
 'away_avg_goals_conceded',
 'win_rate_diff',
 'draw_rate_diff',
 'loss_rate_diff',
 'goals_scored_diff',
 'goals_conceded_diff',
 'matches_played_diff',
 'home_last5_win_rate',
 'away_last5_win_rate',
 'home_last5_avg_goals_scored',
 'away_last5_avg_goals_scored',
 'home_last5_avg_goals_conceded',
 'away_last5_avg_goals_conceded',
 'last5_win_rate_diff',
 'last5_goals_scored_diff',
 'last5_goals_conceded_diff',
 'h2h_matches',
 'h2h_home_win_rate',
 'h2h_away_win_rate',
 'h2h_draw_rate',
 'h2h_win_rate_diff',
 'tournament_category',
 'tournament_continental_championship',
 'tournament_friendly',
 'tournament_nations_league',
 'tournament_other',
 'tournament_world_cup',
 'tournament_world_cup_qualifier',
 'abs_win_rate_diff',
 'abs_last5_diff',
 'abs_h2h_diff',
 'abs_goals_scored_diff',
 'abs_goals_conceded_diff',
 'strength_gap',
 'home_goal_balance',
 'away_goal_balance',
 'goal_balance_diff',
 'home_elo',
 'away_elo',
 'elo_diff']

In [78]:
y = df["result"]

In [79]:
drop_cols = [
    "result",
    "home_score",
    "away_score",
    "date",
    "home_team",
    "away_team",
    "city",
    "country",
    "tournament",
    "tournament_category"
]

X = df.drop(
    columns=[c for c in drop_cols if c in df.columns]
)

In [80]:
df["date"] = pd.to_datetime(df["date"])

df = df.sort_values("date")

In [81]:
split_idx = int(len(df) * 0.8)

train_df = df.iloc[:split_idx]
test_df = df.iloc[split_idx:]

In [82]:
X_train = train_df[X.columns]
X_test = test_df[X.columns]

y_train = train_df["result"]
y_test = test_df["result"]

In [83]:
print(X_train.shape)
print(X_test.shape)

(20195, 53)
(5049, 53)

# Model

In [84]:
rf = RandomForestClassifier(
    n_estimators=300,
    max_depth=15,
    min_samples_split=10,
    random_state=42,
    n_jobs=-1
)

rf.fit(X_train, y_train)

RandomForestClassifier(max_depth=15, min_samples_split=10, n_estimators=300,
                       n_jobs=-1, random_state=42)

In [85]:
y_pred = rf.predict(X_test)

In [86]:
accuracy = accuracy_score(
    y_test,
    y_pred
)

print(f"Accuracy: {accuracy:.4f}")

Accuracy: 0.6029

In [87]:
print(X.columns.tolist())

['neutral', 'year', 'month', 'home_matches_played', 'away_matches_played', 'home_win_rate', 'away_win_rate', 'home_draw_rate', 'away_draw_rate', 'home_loss_rate', 'away_loss_rate', 'home_avg_goals_scored', 'away_avg_goals_scored', 'home_avg_goals_conceded', 'away_avg_goals_conceded', 'win_rate_diff', 'draw_rate_diff', 'loss_rate_diff', 'goals_scored_diff', 'goals_conceded_diff', 'matches_played_diff', 'home_last5_win_rate', 'away_last5_win_rate', 'home_last5_avg_goals_scored', 'away_last5_avg_goals_scored', 'home_last5_avg_goals_conceded', 'away_last5_avg_goals_conceded', 'last5_win_rate_diff', 'last5_goals_scored_diff', 'last5_goals_conceded_diff', 'h2h_matches', 'h2h_home_win_rate', 'h2h_away_win_rate', 'h2h_draw_rate', 'h2h_win_rate_diff', 'tournament_continental_championship', 'tournament_friendly', 'tournament_nations_league', 'tournament_other', 'tournament_world_cup', 'tournament_world_cup_qualifier', 'abs_win_rate_diff', 'abs_last5_diff', 'abs_h2h_diff', 'abs_goals_scored_diff', 'abs_goals_conceded_diff', 'strength_gap', 'home_goal_balance', 'away_goal_balance', 'goal_balance_diff', 'home_elo', 'away_elo', 'elo_diff']

In [88]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

    Away Win       0.59      0.61      0.60      1496
        Draw       0.36      0.04      0.07      1156
    Home Win       0.62      0.87      0.72      2397

    accuracy                           0.60      5049
   macro avg       0.52      0.51      0.47      5049
weighted avg       0.55      0.60      0.54      5049

In [89]:
importance = pd.DataFrame({
    "feature": X.columns,
    "importance": rf.feature_importances_
})

importance.sort_values(
    "importance",
    ascending=False
).head(15)
#Difference Between teams are contributing more

                    feature  importance
52                 elo_diff    0.072031
19      goals_conceded_diff    0.052919
17           loss_rate_diff    0.051685
49        goal_balance_diff    0.050216
15            win_rate_diff    0.035044
18        goals_scored_diff    0.030643
20      matches_played_diff    0.028418
51                 away_elo    0.027974
45  abs_goals_conceded_diff    0.026846
13  home_avg_goals_conceded    0.024893
48        away_goal_balance    0.023581
14  away_avg_goals_conceded    0.023457
50                 home_elo    0.022836
47        home_goal_balance    0.022100
16           draw_rate_diff    0.021315

In [90]:
pd.Series(y_pred).value_counts(normalize=True)

Home Win    0.667261
Away Win    0.307388
Draw        0.025352
Name: proportion, dtype: float64

In [91]:
y_test.value_counts(normalize=True)

result
Home Win    0.474747
Away Win    0.296296
Draw        0.228956
Name: proportion, dtype: float64

## CAT Boost

In [92]:
from catboost import CatBoostClassifier

model = CatBoostClassifier(
    iterations=500,
    depth=6,
    learning_rate=0.05,
    loss_function='MultiClass',
    verbose=0
)

model.fit(X_train, y_train)

preds = model.predict(X_test)

In [93]:
from sklearn.metrics import accuracy_score, classification_report

preds = model.predict(X_test)

print("Accuracy:", accuracy_score(y_test, preds))
print(classification_report(y_test, preds))
#No improvement in accuracy, problem is features not models

Accuracy: 0.6042780748663101
              precision    recall  f1-score   support

    Away Win       0.57      0.65      0.61      1496
        Draw       0.32      0.04      0.07      1156
    Home Win       0.64      0.85      0.73      2397

    accuracy                           0.60      5049
   macro avg       0.51      0.51      0.47      5049
weighted avg       0.54      0.60      0.54      5049

In [ ]:
from catboost import CatBoostClassifier

model = CatBoostClassifier(
    iterations=500,
    depth=6,
    learning_rate=0.05,
    loss_function="MultiClass",
    auto_class_weights="Balanced",
    verbose=0,
    random_state=42
)

model.fit(X_train, y_train)

preds = model.predict(X_test).flatten()

In [ ]:
from sklearn.metrics import accuracy_score, classification_report

preds = model.predict(X_test)

print("Accuracy:", accuracy_score(y_test, preds))
print(classification_report(y_test, preds))

Accuracy: 0.5525846702317291
              precision    recall  f1-score   support

    Away Win       0.55      0.64      0.59      1496
        Draw       0.29      0.29      0.29      1156
    Home Win       0.70      0.63      0.66      2397

    accuracy                           0.55      5049
   macro avg       0.51      0.52      0.51      5049
weighted avg       0.56      0.55      0.55      5049

In [ ]:
from sklearn.metrics import classification_report

report = classification_report(
    y_test,
    preds
)

with open(
    "../reports/catboost_v1_classification_report.txt",
    "w"
) as f:
    f.write(report)

In [ ]:
importance = pd.DataFrame({
    "feature": X_train.columns,
    "importance": model.feature_importances_
})

importance = importance.sort_values(
    "importance",
    ascending=False
)

importance.to_csv(
    "../reports/catboost_v1_feature_importance.csv",
    index=False
)

In [ ]:
import joblib

joblib.dump(
    model,
    "../models/catboost_v2.pkl"
)

['../models/catboost_v1.pkl']

In [ ]:
experiment = pd.DataFrame([
    {
        "model": "CatBoost_V1",
        "accuracy": 0.5526,
        "draw_recall": 0.29,
        "homewin_recall": 0.63,
        "awaywin_recall": 0.64,
        "features": "v3_features"
    }
])

In [ ]:
experiment.to_csv(
    "../reports/experiments.csv",
    mode="a",
    header=False,
    index=False
)